services:
  - type: web
    name: manta-jarvis
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn calendar_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: 'False'
      - key: FLASK_ENV
        value: production
